### ISSUE TITLE
`call_wk_conversion_script` does not work properly because shell is `dash` 

### ISSUE THREAD

**Issue by arentkievits** [hoogenboom-group/scripted-render-pipeline#10]
Currently, the `WK_exporter` script calls the `CATMAID_exporter` to export the data to CATMAID format, then calls the `wk_cuber` to convert it into a WK dataset.

However, calling `source /opt/webknossos/tool/bin/activate` uses dash as shell, which does not support `source`. However, I don't want to set the default shell to bash.

Fix

**Comment by thopp-tudelft** [comment]
which WK_exporter script? it's not part of this repo.

while I recommend to use bash to avoid such issues, if for whatever reason you want to use a different shell it might be worth learning the syntax for said shell: `source` should be `.` https://wiki.ubuntu.com/DashAsBinSh#source

**Comment by arentkievits** [comment]
I pushed all the commits to a new branch called `add-export-script`, I thought it would be good practice to fix the errors before merging with the main branch. 

I did change it to `.` after realizing that it was using a different shell, but it still does not work. What I want to do is activate the python venv through a subprocess and then execute the `wk_cuber` shell script, from the Python script. But I don't think this is the best way to do it:

```
# Virtual environment
        virtualenv_activate = '/opt/webknossos/tool/bin/activate'

        # Call WK shell script in CATMAID project directory
        shell_command = [self.wk_client_script, str(self.catmaid_dir)]
        try:
            # Use 'source' to activate the virtual environment
            activation_cmd = f'. {virtualenv_activate} && {shell_command}'
            # Run the command
            subprocess.run(activation_cmd, shell=True, check=True)
        except subprocess.CalledProcessError as e:
                 print(f"Error: {e}")
```
Gives as output:
```
(.pyvirt) (base) akievits@sonic:~/scripted-render-pipeline-dev$ render_export
/bin/sh: 1: .: cannot open /opt/webknossos/tool/bin/activate: No such file
Error: Command '. /opt/webknossos/tool/bin/activate && ['/opt/webknossos/tools/cube.sh', '/long_term_storage/catmaid_projects/akievits/20230914_RP_exocrine_partial_test']' returned non-zero exit status 2.
(.pyvirt) (base) akievits@sonic:~/scripted-render-pipeline-dev$ 
```

**Comment by thopp-tudelft** [comment]
/opt/webknossos/tools/cube.sh is what is put into self.wk_client_script? this script is a bash script, it does not need the environment to be activated, it does this itself already. it will not run with dash, the first line of the script is the shebang #!/bin/bash which means it will by itself find bash and use it.

it's not needed to source bin/activate, it's not needed to use the shell (shell=True)

here is the script for reference, it is not compatible with dash:
```bash
#!/bin/bash

# convert a catmaid dataset to a webknossos one and put it in the right location
output_location="/long_term_storage/webknossos/binaryData/hoogenboom-group"

input_location="$1"
name="$2"
if [[ !( $input_location && $name ) ]]; then
  echo "usage: $0 [path to catmaid dataset] [project name] [layer name (color)] [voxel size (4,4,90)]"
  exit 1
fi
if [[ $3 ]]; then
  layer_name=$3
else
  layer_name=color
fi
if [[ $4 ]]; then
  voxel_size=$4
else
  voxel_size="4,4,90"
fi
randomfile=$(cd "$input_location" && find . -type f -path "./[0-9]*/[0-9]*_[0-9]*_[0-9]*.*" -print -quit)
if [[ $randomfile ]]; then
  ext="${randomfile##*.}"
  echo "determined file extension: $ext"
  pattern="{zzz}/{yyy}_{xxx}_0.$ext"
else
  pattern="{zzz}/{yyy}_{xxx}_0.png"
fi
set -e

# use virtual environment here
source "${BASH_SOURCE%/*}/bin/activate"
# convert to webknossos format, voxel size is the amount of nm per pixel
echo "running wkcuber.tile_cubing"
python -m wkcuber.tile_cubing --layer_name "$layer_name" \
    --voxel_size "$voxel_size" --input_path_pattern "$pattern" \
    "$input_location" "$output_location/$name"
# compress to save disk space
echo "running wkcuber.compress"
python -m wkcuber.compress --layer_name "$layer_name" "$output_location/$name"
# do downsampling, 128-128-1 means the lowest resolution result will have
# 128 times less pixels in both x and y but not z
echo "running wkcuber.downsampling"
python -m wkcuber.downsampling --max 128-128-1 --sampling_mode isotropic \
    --layer_name "$layer_name" --jobs 16 "$output_location/$name"
```
