### ISSUE TITLE
Directly export to wk cube format

### ISSUE THREAD

**Issue by arentkievits** [hoogenboom-group/scripted-render-pipeline#14]
Currently, `exporter` uses the render `BoxClient` script (in Java), called using `render-python` to export the data to disk as pngs, then calls a shell script to convert to `.wkw` format. This works but is inefficient, since the data is first written to CATMAID format as an intermediate step. We would like to rewrite the `BoxClient` in Python to directly write data to `.wkw` format using the WebKnossos Python API. 

Tasks
- [x] Rewrite `BoxClient` script to Python script that has the same functionality, but writes bboxes to memory and not to disk. 
- [x] Use the [webknossos python api](https://github.com/scalableminds/webknossos-libs) to write the data in memory into .wkw format (on disk)
- [x] Also import metadata in render to webknossos
- [x] Update `WK_exporter.py` to incorporate the changes

**Comment by arentkievits** [comment]
This is a desired feature, but takes less priority than the stitcher

**Comment by arentkievits** [comment]
Ah you can add custom labels...

**Comment by thopp-tudelft** [comment]
yes, if you have more useful labels than the ones we get by default feel free to add them!

**Comment by thopp-tudelft** [comment]
I also did not pay a lot of attention to the accessibility of their colors, you can change them from the default red/yellow/green I selected

**Comment by arentkievits** [comment]
https://github.com/hoogenboom-group/scripted-render-pipeline/commit/9436f29cb221d8925cc9bd132adcccee81e28c89
